# Makefile.in generated by automake 1.15 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2014 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Makefile.am for putty under Unix with Autoconf/Automake.
#
# This file was created by `mkfiles.pl' from the `Recipe' file.
# DO NOT EDIT THIS FILE DIRECTLY; edit Recipe or mkfiles.pl instead.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/putty
pkgincludedir = $(includedir)/putty
pkglibdir = $(libdir)/putty
pkglibexecdir = $(libexecdir)/putty
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
#bin_PROGRAMS = plink$(EXEEXT) pscp$(EXEEXT) \
#	psftp$(EXEEXT) puttygen$(EXEEXT)
bin_PROGRAMS = plink$(EXEEXT) pscp$(EXEEXT) \
	psftp$(EXEEXT) puttygen$(EXEEXT) \
	pageant$(EXEEXT) pterm$(EXEEXT) putty$(EXEEXT) \
	puttytel$(EXEEXT)
#noinst_PROGRAMS = cgtest$(EXEEXT) fuzzterm$(EXEEXT) \
#	osxlaunch$(EXEEXT) testbn$(EXEEXT)
noinst_PROGRAMS = cgtest$(EXEEXT) fuzzterm$(EXEEXT) \
	osxlaunch$(EXEEXT) testbn$(EXEEXT) \
	ptermapp$(EXEEXT) puttyapp$(EXEEXT)
#am__append_1 = -DSOURCE_COMMIT=\"`git --git-dir=$(srcdir)/.git rev-parse HEAD 2>/dev/null`\"
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = uxconfig.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
LIBRARIES = $(noinst_LIBRARIES)
ARFLAGS = cru
AM_V_AR = $(am__v_AR_$(V))
am__v_AR_ = $(am__v_AR_$(AM_DEFAULT_VERBOSITY))
am__v_AR_0 = @echo "  AR      " $@;
am__v_AR_1 = 
libversion_a_AR = $(AR) $(ARFLAGS)
libversion_a_LIBADD =
am_libversion_a_OBJECTS = libversion_a-version.$(OBJEXT)
libversion_a_OBJECTS = $(am_libversion_a_OBJECTS)
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"
PROGRAMS = $(bin_PROGRAMS) $(noinst_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_cgtest_OBJECTS = cgtest.$(OBJEXT) conf.$(OBJEXT) import.$(OBJEXT) \
	misc.$(OBJEXT) notiming.$(OBJEXT) sshaes.$(OBJEXT) \
	sshbcrypt.$(OBJEXT) sshblowf.$(OBJEXT) sshbn.$(OBJEXT) \
	sshdes.$(OBJEXT) sshdss.$(OBJEXT) sshdssg.$(OBJEXT) \
	sshecc.$(OBJEXT) sshecdsag.$(OBJEXT) sshmd5.$(OBJEXT) \
	sshprime.$(OBJEXT) sshpubk.$(OBJEXT) sshrand.$(OBJEXT) \
	sshrsa.$(OBJEXT) sshrsag.$(OBJEXT) sshsh256.$(OBJEXT) \
	sshsh512.$(OBJEXT) sshsha.$(OBJEXT) time.$(OBJEXT) \
	tree234.$(OBJEXT) unix/uxcons.$(OBJEXT) unix/uxgen.$(OBJEXT) \
	unix/uxmisc.$(OBJEXT) unix/uxnogtk.$(OBJEXT) \
	unix/uxnoise.$(OBJEXT) unix/uxstore.$(OBJEXT)
cgtest_OBJECTS = $(am_cgtest_OBJECTS)
cgtest_DEPENDENCIES = libversion.a
am_fuzzterm_OBJECTS = be_none.$(OBJEXT) callback.$(OBJEXT) \
	charset/fromucs.$(OBJEXT) charset/localenc.$(OBJEXT) \
	charset/macenc.$(OBJEXT) charset/mimeenc.$(OBJEXT) \
	charset/sbcs.$(OBJEXT) charset/sbcsdat.$(OBJEXT) \
	charset/slookup.$(OBJEXT) charset/toucs.$(OBJEXT) \
	charset/utf8.$(OBJEXT) charset/xenc.$(OBJEXT) conf.$(OBJEXT) \
	config.$(OBJEXT) dialog.$(OBJEXT) fuzzterm.$(OBJEXT) \
	ldiscucs.$(OBJEXT) logging.$(OBJEXT) minibidi.$(OBJEXT) \
	misc.$(OBJEXT) miscucs.$(OBJEXT) sercfg.$(OBJEXT) \
	settings.$(OBJEXT) terminal.$(OBJEXT) time.$(OBJEXT) \
	timing.$(OBJEXT) tree234.$(OBJEXT) unix/uxcfg.$(OBJEXT) \
	unix/uxmisc.$(OBJEXT) unix/uxnogtk.$(OBJEXT) \
	unix/uxprint.$(OBJEXT) unix/uxstore.$(OBJEXT) \
	unix/uxucs.$(OBJEXT) wcwidth.$(OBJEXT)
fuzzterm_OBJECTS = $(am_fuzzterm_OBJECTS)
fuzzterm_DEPENDENCIES = libversion.a
am_osxlaunch_OBJECTS = unix/osxlaunch.$(OBJEXT)
osxlaunch_OBJECTS = $(am_osxlaunch_OBJECTS)
osxlaunch_LDADD = $(LDADD)
am__pageant_SOURCES_DIST = aqsync.c be_misc.c be_none.c callback.c \
	cmdline.c conf.c misc.c nocproxy.c nogss.c pageant.c proxy.c \
	settings.c sshaes.c sshbn.c sshdes.c sshdss.c sshecc.c \
	sshmd5.c sshpubk.c sshrsa.c sshsh256.c sshsh512.c sshsha.c \
	time.c timing.c tree234.c unix/gtkask.c unix/gtkmisc.c \
	unix/ux_x11.c unix/uxagentc.c unix/uxcons.c unix/uxmisc.c \
	unix/uxnet.c unix/uxpeer.c unix/uxpgnt.c unix/uxproxy.c \
	unix/uxsel.c unix/uxsignal.c unix/uxstore.c x11fwd.c
am_pageant_OBJECTS = aqsync.$(OBJEXT) be_misc.$(OBJEXT) \
	be_none.$(OBJEXT) callback.$(OBJEXT) \
	cmdline.$(OBJEXT) conf.$(OBJEXT) misc.$(OBJEXT) \
	nocproxy.$(OBJEXT) nogss.$(OBJEXT) \
	pageant.$(OBJEXT) proxy.$(OBJEXT) \
	settings.$(OBJEXT) sshaes.$(OBJEXT) \
	sshbn.$(OBJEXT) sshdes.$(OBJEXT) \
	sshdss.$(OBJEXT) sshecc.$(OBJEXT) \
	sshmd5.$(OBJEXT) sshpubk.$(OBJEXT) \
	sshrsa.$(OBJEXT) sshsh256.$(OBJEXT) \
	sshsh512.$(OBJEXT) sshsha.$(OBJEXT) \
	time.$(OBJEXT) timing.$(OBJEXT) \
	tree234.$(OBJEXT) unix/gtkask.$(OBJEXT) \
	unix/gtkmisc.$(OBJEXT) unix/ux_x11.$(OBJEXT) \
	unix/uxagentc.$(OBJEXT) unix/uxcons.$(OBJEXT) \
	unix/uxmisc.$(OBJEXT) unix/uxnet.$(OBJEXT) \
	unix/uxpeer.$(OBJEXT) unix/uxpgnt.$(OBJEXT) \
	unix/uxproxy.$(OBJEXT) unix/uxsel.$(OBJEXT) \
	unix/uxsignal.$(OBJEXT) unix/uxstore.$(OBJEXT) \
	x11fwd.$(OBJEXT)
pageant_OBJECTS = $(am_pageant_OBJECTS)
am__DEPENDENCIES_1 =
pageant_DEPENDENCIES = libversion.a \
	$(am__DEPENDENCIES_1)
am_plink_OBJECTS = aqsync.$(OBJEXT) be_all_s.$(OBJEXT) \
	be_misc.$(OBJEXT) callback.$(OBJEXT) cmdline.$(OBJEXT) \
	conf.$(OBJEXT) cproxy.$(OBJEXT) ldisc.$(OBJEXT) \
	logging.$(OBJEXT) misc.$(OBJEXT) noterm.$(OBJEXT) \
	pgssapi.$(OBJEXT) pinger.$(OBJEXT) portfwd.$(OBJEXT) \
	proxy.$(OBJEXT) raw.$(OBJEXT) rlogin.$(OBJEXT) \
	settings.$(OBJEXT) ssh.$(OBJEXT) sshaes.$(OBJEXT) \
	ssharcf.$(OBJEXT) sshblowf.$(OBJEXT) sshbn.$(OBJEXT) \
	sshccp.$(OBJEXT) sshcrc.$(OBJEXT) sshcrcda.$(OBJEXT) \
	sshdes.$(OBJEXT) sshdh.$(OBJEXT) sshdss.$(OBJEXT) \
	sshecc.$(OBJEXT) sshgssc.$(OBJEXT) sshmd5.$(OBJEXT) \
	sshpubk.$(OBJEXT) sshrand.$(OBJEXT) sshrsa.$(OBJEXT) \
	sshsh256.$(OBJEXT) sshsh512.$(OBJEXT) sshsha.$(OBJEXT) \
	sshshare.$(OBJEXT) sshzlib.$(OBJEXT) telnet.$(OBJEXT) \
	time.$(OBJEXT) timing.$(OBJEXT) tree234.$(OBJEXT) \
	unix/ux_x11.$(OBJEXT) unix/uxagentc.$(OBJEXT) \
	unix/uxcons.$(OBJEXT) unix/uxgss.$(OBJEXT) \
	unix/uxmisc.$(OBJEXT) unix/uxnet.$(OBJEXT) \
	unix/uxnogtk.$(OBJEXT) unix/uxnoise.$(OBJEXT) \
	unix/uxpeer.$(OBJEXT) unix/uxplink.$(OBJEXT) \
	unix/uxproxy.$(OBJEXT) unix/uxsel.$(OBJEXT) \
	unix/uxser.$(OBJEXT) unix/uxshare.$(OBJEXT) \
	unix/uxsignal.$(OBJEXT) unix/uxstore.$(OBJEXT) \
	wildcard.$(OBJEXT) x11fwd.$(OBJEXT)
plink_OBJECTS = $(am_plink_OBJECTS)
plink_DEPENDENCIES = libversion.a
am_pscp_OBJECTS = aqsync.$(OBJEXT) be_misc.$(OBJEXT) be_ssh.$(OBJEXT) \
	callback.$(OBJEXT) cmdline.$(OBJEXT) conf.$(OBJEXT) \
	cproxy.$(OBJEXT) int64.$(OBJEXT) logging.$(OBJEXT) \
	misc.$(OBJEXT) pgssapi.$(OBJEXT) pinger.$(OBJEXT) \
	portfwd.$(OBJEXT) proxy.$(OBJEXT) pscp.$(OBJEXT) \
	settings.$(OBJEXT) sftp.$(OBJEXT) ssh.$(OBJEXT) \
	sshaes.$(OBJEXT) ssharcf.$(OBJEXT) sshblowf.$(OBJEXT) \
	sshbn.$(OBJEXT) sshccp.$(OBJEXT) sshcrc.$(OBJEXT) \
	sshcrcda.$(OBJEXT) sshdes.$(OBJEXT) sshdh.$(OBJEXT) \
	sshdss.$(OBJEXT) sshecc.$(OBJEXT) sshgssc.$(OBJEXT) \
	sshmd5.$(OBJEXT) sshpubk.$(OBJEXT) sshrand.$(OBJEXT) \
	sshrsa.$(OBJEXT) sshsh256.$(OBJEXT) sshsh512.$(OBJEXT) \
	sshsha.$(OBJEXT) sshshare.$(OBJEXT) sshzlib.$(OBJEXT) \
	time.$(OBJEXT) timing.$(OBJEXT) tree234.$(OBJEXT) \
	unix/uxagentc.$(OBJEXT) unix/uxcons.$(OBJEXT) \
	unix/uxgss.$(OBJEXT) unix/uxmisc.$(OBJEXT) \
	unix/uxnet.$(OBJEXT) unix/uxnogtk.$(OBJEXT) \
	unix/uxnoise.$(OBJEXT) unix/uxpeer.$(OBJEXT) \
	unix/uxproxy.$(OBJEXT) unix/uxsel.$(OBJEXT) \
	unix/uxsftp.$(OBJEXT) unix/uxshare.$(OBJEXT) \
	unix/uxstore.$(OBJEXT) wildcard.$(OBJEXT) x11fwd.$(OBJEXT)
pscp_OBJECTS = $(am_pscp_OBJECTS)
pscp_DEPENDENCIES = libversion.a
am_psftp_OBJECTS = aqsync.$(OBJEXT) be_misc.$(OBJEXT) be_ssh.$(OBJEXT) \
	callback.$(OBJEXT) cmdline.$(OBJEXT) conf.$(OBJEXT) \
	cproxy.$(OBJEXT) int64.$(OBJEXT) logging.$(OBJEXT) \
	misc.$(OBJEXT) pgssapi.$(OBJEXT) pinger.$(OBJEXT) \
	portfwd.$(OBJEXT) proxy.$(OBJEXT) psftp.$(OBJEXT) \
	settings.$(OBJEXT) sftp.$(OBJEXT) ssh.$(OBJEXT) \
	sshaes.$(OBJEXT) ssharcf.$(OBJEXT) sshblowf.$(OBJEXT) \
	sshbn.$(OBJEXT) sshccp.$(OBJEXT) sshcrc.$(OBJEXT) \
	sshcrcda.$(OBJEXT) sshdes.$(OBJEXT) sshdh.$(OBJEXT) \
	sshdss.$(OBJEXT) sshecc.$(OBJEXT) sshgssc.$(OBJEXT) \
	sshmd5.$(OBJEXT) sshpubk.$(OBJEXT) sshrand.$(OBJEXT) \
	sshrsa.$(OBJEXT) sshsh256.$(OBJEXT) sshsh512.$(OBJEXT) \
	sshsha.$(OBJEXT) sshshare.$(OBJEXT) sshzlib.$(OBJEXT) \
	time.$(OBJEXT) timing.$(OBJEXT) tree234.$(OBJEXT) \
	unix/uxagentc.$(OBJEXT) unix/uxcons.$(OBJEXT) \
	unix/uxgss.$(OBJEXT) unix/uxmisc.$(OBJEXT) \
	unix/uxnet.$(OBJEXT) unix/uxnogtk.$(OBJEXT) \
	unix/uxnoise.$(OBJEXT) unix/uxpeer.$(OBJEXT) \
	unix/uxproxy.$(OBJEXT) unix/uxsel.$(OBJEXT) \
	unix/uxsftp.$(OBJEXT) unix/uxshare.$(OBJEXT) \
	unix/uxstore.$(OBJEXT) wildcard.$(OBJEXT) x11fwd.$(OBJEXT)
psftp_OBJECTS = $(am_psftp_OBJECTS)
psftp_DEPENDENCIES = libversion.a
am__pterm_SOURCES_DIST = be_none.c callback.c charset/fromucs.c \
	charset/localenc.c charset/macenc.c charset/mimeenc.c \
	charset/sbcs.c charset/sbcsdat.c charset/slookup.c \
	charset/toucs.c charset/utf8.c charset/xenc.c cmdline.c conf.c \
	config.c dialog.c ldisc.c ldiscucs.c logging.c minibidi.c \
	misc.c miscucs.c nocproxy.c nogss.c sercfg.c settings.c \
	terminal.c time.c timing.c tree234.c unix/gtkcfg.c \
	unix/gtkcols.c unix/gtkcomm.c unix/gtkdlg.c unix/gtkfont.c \
	unix/gtkmain.c unix/gtkmisc.c unix/gtkwin.c unix/uxcfg.c \
	unix/uxmisc.c unix/uxprint.c unix/uxpterm.c unix/uxpty.c \
	unix/uxsel.c unix/uxsignal.c unix/uxstore.c unix/uxucs.c \
	unix/x11misc.c unix/xkeysym.c unix/xpmptcfg.c unix/xpmpterm.c \
	wcwidth.c
am_pterm_OBJECTS = be_none.$(OBJEXT) callback.$(OBJEXT) \
	charset/fromucs.$(OBJEXT) \
	charset/localenc.$(OBJEXT) \
	charset/macenc.$(OBJEXT) \
	charset/mimeenc.$(OBJEXT) \
	charset/sbcs.$(OBJEXT) \
	charset/sbcsdat.$(OBJEXT) \
	charset/slookup.$(OBJEXT) \
	charset/toucs.$(OBJEXT) charset/utf8.$(OBJEXT) \
	charset/xenc.$(OBJEXT) cmdline.$(OBJEXT) \
	conf.$(OBJEXT) config.$(OBJEXT) \
	dialog.$(OBJEXT) ldisc.$(OBJEXT) \
	ldiscucs.$(OBJEXT) logging.$(OBJEXT) \
	minibidi.$(OBJEXT) misc.$(OBJEXT) \
	miscucs.$(OBJEXT) nocproxy.$(OBJEXT) \
	nogss.$(OBJEXT) sercfg.$(OBJEXT) \
	settings.$(OBJEXT) terminal.$(OBJEXT) \
	time.$(OBJEXT) timing.$(OBJEXT) \
	tree234.$(OBJEXT) unix/gtkcfg.$(OBJEXT) \
	unix/gtkcols.$(OBJEXT) unix/gtkcomm.$(OBJEXT) \
	unix/gtkdlg.$(OBJEXT) unix/gtkfont.$(OBJEXT) \
	unix/gtkmain.$(OBJEXT) unix/gtkmisc.$(OBJEXT) \
	unix/gtkwin.$(OBJEXT) unix/uxcfg.$(OBJEXT) \
	unix/uxmisc.$(OBJEXT) unix/uxprint.$(OBJEXT) \
	unix/uxpterm.$(OBJEXT) unix/uxpty.$(OBJEXT) \
	unix/uxsel.$(OBJEXT) unix/uxsignal.$(OBJEXT) \
	unix/uxstore.$(OBJEXT) unix/uxucs.$(OBJEXT) \
	unix/x11misc.$(OBJEXT) unix/xkeysym.$(OBJEXT) \
	unix/xpmptcfg.$(OBJEXT) unix/xpmpterm.$(OBJEXT) \
	wcwidth.$(OBJEXT)
pterm_OBJECTS = $(am_pterm_OBJECTS)
pterm_DEPENDENCIES = libversion.a $(am__DEPENDENCIES_1)
am__ptermapp_SOURCES_DIST = be_none.c callback.c charset/fromucs.c \
	charset/localenc.c charset/macenc.c charset/mimeenc.c \
	charset/sbcs.c charset/sbcsdat.c charset/slookup.c \
	charset/toucs.c charset/utf8.c charset/xenc.c cmdline.c conf.c \
	config.c dialog.c ldisc.c ldiscucs.c logging.c minibidi.c \
	misc.c miscucs.c nocproxy.c nogss.c sercfg.c settings.c \
	terminal.c time.c timing.c tree234.c unix/gtkapp.c \
	unix/gtkcfg.c unix/gtkcols.c unix/gtkcomm.c unix/gtkdlg.c \
	unix/gtkfont.c unix/gtkmisc.c unix/gtkwin.c unix/uxcfg.c \
	unix/uxmisc.c unix/uxprint.c unix/uxpterm.c unix/uxpty.c \
	unix/uxsel.c unix/uxsignal.c unix/uxstore.c unix/uxucs.c \
	unix/x11misc.c unix/xkeysym.c unix/xpmptcfg.c unix/xpmpterm.c \
	wcwidth.c
am_ptermapp_OBJECTS = be_none.$(OBJEXT) \
	callback.$(OBJEXT) charset/fromucs.$(OBJEXT) \
	charset/localenc.$(OBJEXT) \
	charset/macenc.$(OBJEXT) \
	charset/mimeenc.$(OBJEXT) \
	charset/sbcs.$(OBJEXT) \
	charset/sbcsdat.$(OBJEXT) \
	charset/slookup.$(OBJEXT) \
	charset/toucs.$(OBJEXT) charset/utf8.$(OBJEXT) \
	charset/xenc.$(OBJEXT) cmdline.$(OBJEXT) \
	conf.$(OBJEXT) config.$(OBJEXT) \
	dialog.$(OBJEXT) ldisc.$(OBJEXT) \
	ldiscucs.$(OBJEXT) logging.$(OBJEXT) \
	minibidi.$(OBJEXT) misc.$(OBJEXT) \
	miscucs.$(OBJEXT) nocproxy.$(OBJEXT) \
	nogss.$(OBJEXT) sercfg.$(OBJEXT) \
	settings.$(OBJEXT) terminal.$(OBJEXT) \
	time.$(OBJEXT) timing.$(OBJEXT) \
	tree234.$(OBJEXT) unix/gtkapp.$(OBJEXT) \
	unix/gtkcfg.$(OBJEXT) unix/gtkcols.$(OBJEXT) \
	unix/gtkcomm.$(OBJEXT) unix/gtkdlg.$(OBJEXT) \
	unix/gtkfont.$(OBJEXT) unix/gtkmisc.$(OBJEXT) \
	unix/gtkwin.$(OBJEXT) unix/uxcfg.$(OBJEXT) \
	unix/uxmisc.$(OBJEXT) unix/uxprint.$(OBJEXT) \
	unix/uxpterm.$(OBJEXT) unix/uxpty.$(OBJEXT) \
	unix/uxsel.$(OBJEXT) unix/uxsignal.$(OBJEXT) \
	unix/uxstore.$(OBJEXT) unix/uxucs.$(OBJEXT) \
	unix/x11misc.$(OBJEXT) unix/xkeysym.$(OBJEXT) \
	unix/xpmptcfg.$(OBJEXT) unix/xpmpterm.$(OBJEXT) \
	wcwidth.$(OBJEXT)
ptermapp_OBJECTS = $(am_ptermapp_OBJECTS)
ptermapp_DEPENDENCIES = libversion.a \
	$(am__DEPENDENCIES_1)
am__putty_SOURCES_DIST = aqsync.c be_all_s.c be_misc.c callback.c \
	charset/fromucs.c charset/localenc.c charset/macenc.c \
	charset/mimeenc.c charset/sbcs.c charset/sbcsdat.c \
	charset/slookup.c charset/toucs.c charset/utf8.c \
	charset/xenc.c cmdline.c conf.c config.c cproxy.c dialog.c \
	ldisc.c ldiscucs.c logging.c minibidi.c misc.c miscucs.c \
	pgssapi.c pinger.c portfwd.c proxy.c raw.c rlogin.c sercfg.c \
	settings.c ssh.c sshaes.c ssharcf.c sshblowf.c sshbn.c \
	sshccp.c sshcrc.c sshcrcda.c sshdes.c sshdh.c sshdss.c \
	sshecc.c sshgssc.c sshmd5.c sshpubk.c sshrand.c sshrsa.c \
	sshsh256.c sshsh512.c sshsha.c sshshare.c sshzlib.c telnet.c \
	terminal.c time.c timing.c tree234.c unix/gtkcfg.c \
	unix/gtkcols.c unix/gtkcomm.c unix/gtkdlg.c unix/gtkfont.c \
	unix/gtkmain.c unix/gtkmisc.c unix/gtkwin.c unix/ux_x11.c \
	unix/uxagentc.c unix/uxcfg.c unix/uxgss.c unix/uxmisc.c \
	unix/uxnet.c unix/uxnoise.c unix/uxpeer.c unix/uxprint.c \
	unix/uxproxy.c unix/uxputty.c unix/uxsel.c unix/uxser.c \
	unix/uxshare.c unix/uxsignal.c unix/uxstore.c unix/uxucs.c \
	unix/x11misc.c unix/xkeysym.c unix/xpmpucfg.c unix/xpmputty.c \
	wcwidth.c wildcard.c x11fwd.c
am_putty_OBJECTS = aqsync.$(OBJEXT) be_all_s.$(OBJEXT) \
	be_misc.$(OBJEXT) callback.$(OBJEXT) \
	charset/fromucs.$(OBJEXT) \
	charset/localenc.$(OBJEXT) \
	charset/macenc.$(OBJEXT) \
	charset/mimeenc.$(OBJEXT) \
	charset/sbcs.$(OBJEXT) \
	charset/sbcsdat.$(OBJEXT) \
	charset/slookup.$(OBJEXT) \
	charset/toucs.$(OBJEXT) charset/utf8.$(OBJEXT) \
	charset/xenc.$(OBJEXT) cmdline.$(OBJEXT) \
	conf.$(OBJEXT) config.$(OBJEXT) \
	cproxy.$(OBJEXT) dialog.$(OBJEXT) \
	ldisc.$(OBJEXT) ldiscucs.$(OBJEXT) \
	logging.$(OBJEXT) minibidi.$(OBJEXT) \
	misc.$(OBJEXT) miscucs.$(OBJEXT) \
	pgssapi.$(OBJEXT) pinger.$(OBJEXT) \
	portfwd.$(OBJEXT) proxy.$(OBJEXT) raw.$(OBJEXT) \
	rlogin.$(OBJEXT) sercfg.$(OBJEXT) \
	settings.$(OBJEXT) ssh.$(OBJEXT) \
	sshaes.$(OBJEXT) ssharcf.$(OBJEXT) \
	sshblowf.$(OBJEXT) sshbn.$(OBJEXT) \
	sshccp.$(OBJEXT) sshcrc.$(OBJEXT) \
	sshcrcda.$(OBJEXT) sshdes.$(OBJEXT) \
	sshdh.$(OBJEXT) sshdss.$(OBJEXT) \
	sshecc.$(OBJEXT) sshgssc.$(OBJEXT) \
	sshmd5.$(OBJEXT) sshpubk.$(OBJEXT) \
	sshrand.$(OBJEXT) sshrsa.$(OBJEXT) \
	sshsh256.$(OBJEXT) sshsh512.$(OBJEXT) \
	sshsha.$(OBJEXT) sshshare.$(OBJEXT) \
	sshzlib.$(OBJEXT) telnet.$(OBJEXT) \
	terminal.$(OBJEXT) time.$(OBJEXT) \
	timing.$(OBJEXT) tree234.$(OBJEXT) \
	unix/gtkcfg.$(OBJEXT) unix/gtkcols.$(OBJEXT) \
	unix/gtkcomm.$(OBJEXT) unix/gtkdlg.$(OBJEXT) \
	unix/gtkfont.$(OBJEXT) unix/gtkmain.$(OBJEXT) \
	unix/gtkmisc.$(OBJEXT) unix/gtkwin.$(OBJEXT) \
	unix/ux_x11.$(OBJEXT) unix/uxagentc.$(OBJEXT) \
	unix/uxcfg.$(OBJEXT) unix/uxgss.$(OBJEXT) \
	unix/uxmisc.$(OBJEXT) unix/uxnet.$(OBJEXT) \
	unix/uxnoise.$(OBJEXT) unix/uxpeer.$(OBJEXT) \
	unix/uxprint.$(OBJEXT) unix/uxproxy.$(OBJEXT) \
	unix/uxputty.$(OBJEXT) unix/uxsel.$(OBJEXT) \
	unix/uxser.$(OBJEXT) unix/uxshare.$(OBJEXT) \
	unix/uxsignal.$(OBJEXT) unix/uxstore.$(OBJEXT) \
	unix/uxucs.$(OBJEXT) unix/x11misc.$(OBJEXT) \
	unix/xkeysym.$(OBJEXT) unix/xpmpucfg.$(OBJEXT) \
	unix/xpmputty.$(OBJEXT) wcwidth.$(OBJEXT) \
	wildcard.$(OBJEXT) x11fwd.$(OBJEXT)
putty_OBJECTS = $(am_putty_OBJECTS)
putty_DEPENDENCIES = libversion.a $(am__DEPENDENCIES_1)
am__puttyapp_SOURCES_DIST = aqsync.c be_all_s.c be_misc.c callback.c \
	charset/fromucs.c charset/localenc.c charset/macenc.c \
	charset/mimeenc.c charset/sbcs.c charset/sbcsdat.c \
	charset/slookup.c charset/toucs.c charset/utf8.c \
	charset/xenc.c cmdline.c conf.c config.c cproxy.c dialog.c \
	ldisc.c ldiscucs.c logging.c minibidi.c misc.c miscucs.c \
	pgssapi.c pinger.c portfwd.c proxy.c raw.c rlogin.c sercfg.c \
	settings.c ssh.c sshaes.c ssharcf.c sshblowf.c sshbn.c \
	sshccp.c sshcrc.c sshcrcda.c sshdes.c sshdh.c sshdss.c \
	sshecc.c sshgssc.c sshmd5.c sshpubk.c sshrand.c sshrsa.c \
	sshsh256.c sshsh512.c sshsha.c sshshare.c sshzlib.c telnet.c \
	terminal.c time.c timing.c tree234.c unix/gtkapp.c \
	unix/gtkcfg.c unix/gtkcols.c unix/gtkcomm.c unix/gtkdlg.c \
	unix/gtkfont.c unix/gtkmisc.c unix/gtkwin.c unix/ux_x11.c \
	unix/uxagentc.c unix/uxcfg.c unix/uxgss.c unix/uxmisc.c \
	unix/uxnet.c unix/uxnoise.c unix/uxpeer.c unix/uxprint.c \
	unix/uxproxy.c unix/uxputty.c unix/uxsel.c unix/uxser.c \
	unix/uxshare.c unix/uxsignal.c unix/uxstore.c unix/uxucs.c \
	unix/x11misc.c unix/xkeysym.c unix/xpmpucfg.c unix/xpmputty.c \
	wcwidth.c wildcard.c x11fwd.c
am_puttyapp_OBJECTS = aqsync.$(OBJEXT) \
	be_all_s.$(OBJEXT) be_misc.$(OBJEXT) \
	callback.$(OBJEXT) charset/fromucs.$(OBJEXT) \
	charset/localenc.$(OBJEXT) \
	charset/macenc.$(OBJEXT) \
	charset/mimeenc.$(OBJEXT) \
	charset/sbcs.$(OBJEXT) \
	charset/sbcsdat.$(OBJEXT) \
	charset/slookup.$(OBJEXT) \
	charset/toucs.$(OBJEXT) charset/utf8.$(OBJEXT) \
	charset/xenc.$(OBJEXT) cmdline.$(OBJEXT) \
	conf.$(OBJEXT) config.$(OBJEXT) \
	cproxy.$(OBJEXT) dialog.$(OBJEXT) \
	ldisc.$(OBJEXT) ldiscucs.$(OBJEXT) \
	logging.$(OBJEXT) minibidi.$(OBJEXT) \
	misc.$(OBJEXT) miscucs.$(OBJEXT) \
	pgssapi.$(OBJEXT) pinger.$(OBJEXT) \
	portfwd.$(OBJEXT) proxy.$(OBJEXT) raw.$(OBJEXT) \
	rlogin.$(OBJEXT) sercfg.$(OBJEXT) \
	settings.$(OBJEXT) ssh.$(OBJEXT) \
	sshaes.$(OBJEXT) ssharcf.$(OBJEXT) \
	sshblowf.$(OBJEXT) sshbn.$(OBJEXT) \
	sshccp.$(OBJEXT) sshcrc.$(OBJEXT) \
	sshcrcda.$(OBJEXT) sshdes.$(OBJEXT) \
	sshdh.$(OBJEXT) sshdss.$(OBJEXT) \
	sshecc.$(OBJEXT) sshgssc.$(OBJEXT) \
	sshmd5.$(OBJEXT) sshpubk.$(OBJEXT) \
	sshrand.$(OBJEXT) sshrsa.$(OBJEXT) \
	sshsh256.$(OBJEXT) sshsh512.$(OBJEXT) \
	sshsha.$(OBJEXT) sshshare.$(OBJEXT) \
	sshzlib.$(OBJEXT) telnet.$(OBJEXT) \
	terminal.$(OBJEXT) time.$(OBJEXT) \
	timing.$(OBJEXT) tree234.$(OBJEXT) \
	unix/gtkapp.$(OBJEXT) unix/gtkcfg.$(OBJEXT) \
	unix/gtkcols.$(OBJEXT) unix/gtkcomm.$(OBJEXT) \
	unix/gtkdlg.$(OBJEXT) unix/gtkfont.$(OBJEXT) \
	unix/gtkmisc.$(OBJEXT) unix/gtkwin.$(OBJEXT) \
	unix/ux_x11.$(OBJEXT) unix/uxagentc.$(OBJEXT) \
	unix/uxcfg.$(OBJEXT) unix/uxgss.$(OBJEXT) \
	unix/uxmisc.$(OBJEXT) unix/uxnet.$(OBJEXT) \
	unix/uxnoise.$(OBJEXT) unix/uxpeer.$(OBJEXT) \
	unix/uxprint.$(OBJEXT) unix/uxproxy.$(OBJEXT) \
	unix/uxputty.$(OBJEXT) unix/uxsel.$(OBJEXT) \
	unix/uxser.$(OBJEXT) unix/uxshare.$(OBJEXT) \
	unix/uxsignal.$(OBJEXT) unix/uxstore.$(OBJEXT) \
	unix/uxucs.$(OBJEXT) unix/x11misc.$(OBJEXT) \
	unix/xkeysym.$(OBJEXT) unix/xpmpucfg.$(OBJEXT) \
	unix/xpmputty.$(OBJEXT) wcwidth.$(OBJEXT) \
	wildcard.$(OBJEXT) x11fwd.$(OBJEXT)
puttyapp_OBJECTS = $(am_puttyapp_OBJECTS)
puttyapp_DEPENDENCIES = libversion.a \
	$(am__DEPENDENCIES_1)
am_puttygen_OBJECTS = cmdgen.$(OBJEXT) conf.$(OBJEXT) import.$(OBJEXT) \
	misc.$(OBJEXT) notiming.$(OBJEXT) sshaes.$(OBJEXT) \
	sshbcrypt.$(OBJEXT) sshblowf.$(OBJEXT) sshbn.$(OBJEXT) \
	sshdes.$(OBJEXT) sshdss.$(OBJEXT) sshdssg.$(OBJEXT) \
	sshecc.$(OBJEXT) sshecdsag.$(OBJEXT) sshmd5.$(OBJEXT) \
	sshprime.$(OBJEXT) sshpubk.$(OBJEXT) sshrand.$(OBJEXT) \
	sshrsa.$(OBJEXT) sshrsag.$(OBJEXT) sshsh256.$(OBJEXT) \
	sshsh512.$(OBJEXT) sshsha.$(OBJEXT) time.$(OBJEXT) \
	tree234.$(OBJEXT) unix/uxcons.$(OBJEXT) unix/uxgen.$(OBJEXT) \
	unix/uxmisc.$(OBJEXT) unix/uxnogtk.$(OBJEXT) \
	unix/uxnoise.$(OBJEXT) unix/uxstore.$(OBJEXT)
puttygen_OBJECTS = $(am_puttygen_OBJECTS)
puttygen_DEPENDENCIES = libversion.a
am__puttytel_SOURCES_DIST = be_misc.c be_nos_s.c callback.c \
	charset/fromucs.c charset/localenc.c charset/macenc.c \
	charset/mimeenc.c charset/sbcs.c charset/sbcsdat.c \
	charset/slookup.c charset/toucs.c charset/utf8.c \
	charset/xenc.c cmdline.c conf.c config.c dialog.c ldisc.c \
	ldiscucs.c logging.c minibidi.c misc.c miscucs.c nocproxy.c \
	nogss.c pinger.c proxy.c raw.c rlogin.c sercfg.c settings.c \
	telnet.c terminal.c time.c timing.c tree234.c unix/gtkcfg.c \
	unix/gtkcols.c unix/gtkcomm.c unix/gtkdlg.c unix/gtkfont.c \
	unix/gtkmain.c unix/gtkmisc.c unix/gtkwin.c unix/uxcfg.c \
	unix/uxmisc.c unix/uxnet.c unix/uxpeer.c unix/uxprint.c \
	unix/uxproxy.c unix/uxputty.c unix/uxsel.c unix/uxser.c \
	unix/uxsignal.c unix/uxstore.c unix/uxucs.c unix/x11misc.c \
	unix/xkeysym.c unix/xpmpucfg.c unix/xpmputty.c wcwidth.c
am_puttytel_OBJECTS = be_misc.$(OBJEXT) \
	be_nos_s.$(OBJEXT) callback.$(OBJEXT) \
	charset/fromucs.$(OBJEXT) \
	charset/localenc.$(OBJEXT) \
	charset/macenc.$(OBJEXT) \
	charset/mimeenc.$(OBJEXT) \
	charset/sbcs.$(OBJEXT) \
	charset/sbcsdat.$(OBJEXT) \
	charset/slookup.$(OBJEXT) \
	charset/toucs.$(OBJEXT) charset/utf8.$(OBJEXT) \
	charset/xenc.$(OBJEXT) cmdline.$(OBJEXT) \
	conf.$(OBJEXT) config.$(OBJEXT) \
	dialog.$(OBJEXT) ldisc.$(OBJEXT) \
	ldiscucs.$(OBJEXT) logging.$(OBJEXT) \
	minibidi.$(OBJEXT) misc.$(OBJEXT) \
	miscucs.$(OBJEXT) nocproxy.$(OBJEXT) \
	nogss.$(OBJEXT) pinger.$(OBJEXT) \
	proxy.$(OBJEXT) raw.$(OBJEXT) rlogin.$(OBJEXT) \
	sercfg.$(OBJEXT) settings.$(OBJEXT) \
	telnet.$(OBJEXT) terminal.$(OBJEXT) \
	time.$(OBJEXT) timing.$(OBJEXT) \
	tree234.$(OBJEXT) unix/gtkcfg.$(OBJEXT) \
	unix/gtkcols.$(OBJEXT) unix/gtkcomm.$(OBJEXT) \
	unix/gtkdlg.$(OBJEXT) unix/gtkfont.$(OBJEXT) \
	unix/gtkmain.$(OBJEXT) unix/gtkmisc.$(OBJEXT) \
	unix/gtkwin.$(OBJEXT) unix/uxcfg.$(OBJEXT) \
	unix/uxmisc.$(OBJEXT) unix/uxnet.$(OBJEXT) \
	unix/uxpeer.$(OBJEXT) unix/uxprint.$(OBJEXT) \
	unix/uxproxy.$(OBJEXT) unix/uxputty.$(OBJEXT) \
	unix/uxsel.$(OBJEXT) unix/uxser.$(OBJEXT) \
	unix/uxsignal.$(OBJEXT) unix/uxstore.$(OBJEXT) \
	unix/uxucs.$(OBJEXT) unix/x11misc.$(OBJEXT) \
	unix/xkeysym.$(OBJEXT) unix/xpmpucfg.$(OBJEXT) \
	unix/xpmputty.$(OBJEXT) wcwidth.$(OBJEXT)
puttytel_OBJECTS = $(am_puttytel_OBJECTS)
puttytel_DEPENDENCIES = libversion.a \
	$(am__DEPENDENCIES_1)
am_testbn_OBJECTS = conf.$(OBJEXT) misc.$(OBJEXT) sshbn.$(OBJEXT) \
	testbn.$(OBJEXT) tree234.$(OBJEXT) unix/uxmisc.$(OBJEXT) \
	unix/uxnogtk.$(OBJEXT)
testbn_OBJECTS = $(am_testbn_OBJECTS)
testbn_DEPENDENCIES = libversion.a
SCRIPTS = $(noinst_SCRIPTS)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(libversion_a_SOURCES) $(cgtest_SOURCES) \
	$(fuzzterm_SOURCES) $(osxlaunch_SOURCES) $(pageant_SOURCES) \
	$(plink_SOURCES) $(pscp_SOURCES) $(psftp_SOURCES) \
	$(pterm_SOURCES) $(ptermapp_SOURCES) $(putty_SOURCES) \
	$(puttyapp_SOURCES) $(puttygen_SOURCES) $(puttytel_SOURCES) \
	$(testbn_SOURCES)
DIST_SOURCES = $(libversion_a_SOURCES) $(cgtest_SOURCES) \
	$(fuzzterm_SOURCES) $(osxlaunch_SOURCES) \
	$(am__pageant_SOURCES_DIST) $(plink_SOURCES) $(pscp_SOURCES) \
	$(psftp_SOURCES) $(am__pterm_SOURCES_DIST) \
	$(am__ptermapp_SOURCES_DIST) $(am__putty_SOURCES_DIST) \
	$(am__puttyapp_SOURCES_DIST) $(puttygen_SOURCES) \
	$(am__puttytel_SOURCES_DIST) $(testbn_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
man1dir = $(mandir)/man1
NROFF = nroff
MANS = $(man1_MANS)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)uxconfig.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/uxconfig.in README \
	ar-lib compile depcomp install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /media/B/cjn/putty-0.70/missing aclocal-1.15
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AR = ar
AUTOCONF = ${SHELL} /media/B/cjn/putty-0.70/missing autoconf
AUTOHEADER = ${SHELL} /media/B/cjn/putty-0.70/missing autoheader
AUTOMAKE = ${SHELL} /media/B/cjn/putty-0.70/missing automake-1.15
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
GREP = /usr/bin/grep
GTK1_CONFIG = 
GTK_CFLAGS = -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include 
GTK_LIBS = -lX11 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -ldl 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /media/B/cjn/putty-0.70/missing makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJEXT = o
PACKAGE = putty
PACKAGE_BUGREPORT = 
PACKAGE_NAME = putty
PACKAGE_STRING = putty 0.70
PACKAGE_TARNAME = putty
PACKAGE_URL = 
PACKAGE_VERSION = 0.70
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
RANLIB = ranlib
SETID_CMD = 
SETID_MODE = 
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 0.70
WARNINGOPTS = -Wall -Werror
abs_builddir = /media/B/cjn/putty-0.70
abs_srcdir = /media/B/cjn/putty-0.70
abs_top_builddir = /media/B/cjn/putty-0.70
abs_top_srcdir = /media/B/cjn/putty-0.70
ac_ct_AR = ar
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /media/B/cjn/putty-0.70/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = subdir-objects
allsources = aqsync.c be_all_s.c be_misc.c be_none.c be_nos_s.c be_ssh.c \
		callback.c cgtest.c charset/charset.h charset/enum.c \
		charset/fromucs.c charset/internal.h charset/localenc.c \
		charset/macenc.c charset/mimeenc.c charset/sbcs.c \
		charset/sbcsdat.c charset/slookup.c charset/toucs.c \
		charset/utf8.c charset/xenc.c cmdgen.c cmdline.c conf.c \
		config.c cproxy.c dialog.c dialog.h errsock.c fuzzterm.c \
		import.c int64.c int64.h ldisc.c ldisc.h ldiscucs.c \
		licence.h logging.c minibidi.c misc.c misc.h miscucs.c \
		network.h nocproxy.c nogss.c noshare.c noterm.c notiming.c \
		pageant.c pageant.h pgssapi.c pgssapi.h pinger.c portfwd.c \
		proxy.c proxy.h pscp.c psftp.c psftp.h putty.h puttymem.h \
		puttyps.h raw.c rlogin.c sercfg.c settings.c sftp.c sftp.h \
		ssh.c ssh.h sshaes.c ssharcf.c sshbcrypt.c sshblowf.c \
		sshblowf.h sshbn.c sshbn.h sshccp.c sshcrc.c sshcrcda.c \
		sshdes.c sshdh.c sshdss.c sshdssg.c sshecc.c sshecdsag.c \
		sshgss.h sshgssc.c sshgssc.h sshmd5.c sshprime.c sshpubk.c \
		sshrand.c sshrsa.c sshrsag.c sshsh256.c sshsh512.c sshsha.c \
		sshshare.c sshzlib.c storage.h telnet.c terminal.c \
		terminal.h testbn.c time.c timing.c tree234.c tree234.h \
		unix/gtkapp.c unix/gtkask.c unix/gtkcfg.c unix/gtkcols.c \
		unix/gtkcols.h unix/gtkcomm.c unix/gtkcompat.h unix/gtkdlg.c \
		unix/gtkfont.c unix/gtkfont.h unix/gtkmain.c unix/gtkmisc.c \
		unix/gtkmisc.h unix/gtkwin.c unix/osxlaunch.c unix/unix.h \
		unix/ux_x11.c unix/uxagentc.c unix/uxcfg.c unix/uxcons.c \
		unix/uxgen.c unix/uxgss.c unix/uxmisc.c unix/uxnet.c \
		unix/uxnogtk.c unix/uxnoise.c unix/uxpeer.c unix/uxpgnt.c \
		unix/uxplink.c unix/uxprint.c unix/uxproxy.c unix/uxpterm.c \
		unix/uxpty.c unix/uxputty.c unix/uxsel.c unix/uxser.c \
		unix/uxsftp.c unix/uxshare.c unix/uxsignal.c unix/uxstore.c \
		unix/uxucs.c unix/x11misc.c unix/x11misc.h unix/xkeysym.c \
		unix/xpmptcfg.c unix/xpmpterm.c unix/xpmpucfg.c \
		unix/xpmputty.c version.c version.h wcwidth.c wildcard.c \
		windows/pageant.rc windows/plink.rc windows/pscp.rc \
		windows/psftp.rc windows/putty.rc windows/puttygen.rc \
		windows/puttytel.rc windows/rcstuff.h windows/sizetip.c \
		windows/version.rc2 windows/win_res.h windows/win_res.rc2 \
		windows/wincapi.c windows/wincapi.h windows/wincfg.c \
		windows/wincons.c windows/winctrls.c windows/windefs.c \
		windows/windlg.c windows/window.c windows/wingss.c \
		windows/winhandl.c windows/winhelp.c windows/winhelp.h \
		windows/winhsock.c windows/winjump.c windows/winmisc.c \
		windows/winnet.c windows/winnoise.c windows/winnojmp.c \
		windows/winnpc.c windows/winnps.c windows/winpgen.c \
		windows/winpgnt.c windows/winpgntc.c windows/winplink.c \
		windows/winprint.c windows/winproxy.c windows/winsecur.c \
		windows/winsecur.h windows/winser.c windows/winsftp.c \
		windows/winshare.c windows/winstore.c windows/winstuff.h \
		windows/wintime.c windows/winucs.c windows/winutils.c \
		windows/winx11.c x11fwd.c

AM_CPPFLAGS = -I$(srcdir)/./ -I$(srcdir)/charset/ -I$(srcdir)/windows/ \
		-I$(srcdir)/unix/

#AM_CFLAGS = $(COMPAT) $(XFLAGS) $(WARNINGOPTS)
AM_CFLAGS = $(GTK_CFLAGS) $(COMPAT) $(XFLAGS) $(WARNINGOPTS)
libversion_a_SOURCES = version.c
libversion_a_CFLAGS = $(COMPAT) $(XFLAGS) $(WARNINGOPTS) \
	$(am__append_1)
noinst_LIBRARIES = libversion.a
cgtest_SOURCES = cgtest.c conf.c import.c misc.c notiming.c sshaes.c \
		sshbcrypt.c sshblowf.c sshbn.c sshdes.c sshdss.c sshdssg.c \
		sshecc.c sshecdsag.c sshmd5.c sshprime.c sshpubk.c sshrand.c \
		sshrsa.c sshrsag.c sshsh256.c sshsh512.c sshsha.c time.c \
		tree234.c unix/uxcons.c unix/uxgen.c unix/uxmisc.c \
		unix/uxnogtk.c unix/uxnoise.c unix/uxstore.c

cgtest_LDADD = libversion.a
fuzzterm_SOURCES = be_none.c callback.c charset/fromucs.c charset/localenc.c \
		charset/macenc.c charset/mimeenc.c charset/sbcs.c \
		charset/sbcsdat.c charset/slookup.c charset/toucs.c \
		charset/utf8.c charset/xenc.c conf.c config.c dialog.c \
		fuzzterm.c ldiscucs.c logging.c minibidi.c misc.c miscucs.c \
		sercfg.c settings.c terminal.c time.c timing.c tree234.c \
		unix/uxcfg.c unix/uxmisc.c unix/uxnogtk.c unix/uxprint.c \
		unix/uxstore.c unix/uxucs.c wcwidth.c

fuzzterm_LDADD = libversion.a
osxlaunch_SOURCES = unix/osxlaunch.c
pageant_SOURCES = aqsync.c be_misc.c be_none.c callback.c cmdline.c conf.c \
		misc.c nocproxy.c nogss.c pageant.c proxy.c settings.c \
		sshaes.c sshbn.c sshdes.c sshdss.c sshecc.c sshmd5.c \
		sshpubk.c sshrsa.c sshsh256.c sshsh512.c sshsha.c time.c \
		timing.c tree234.c unix/gtkask.c unix/gtkmisc.c \
		unix/ux_x11.c unix/uxagentc.c unix/uxcons.c unix/uxmisc.c \
		unix/uxnet.c unix/uxpeer.c unix/uxpgnt.c unix/uxproxy.c \
		unix/uxsel.c unix/uxsignal.c unix/uxstore.c x11fwd.c

pageant_LDADD = libversion.a $(GTK_LIBS)
plink_SOURCES = aqsync.c be_all_s.c be_misc.c callback.c cmdline.c conf.c \
		cproxy.c ldisc.c logging.c misc.c noterm.c pgssapi.c \
		pinger.c portfwd.c proxy.c raw.c rlogin.c settings.c ssh.c \
		sshaes.c ssharcf.c sshblowf.c sshbn.c sshccp.c sshcrc.c \
		sshcrcda.c sshdes.c sshdh.c sshdss.c sshecc.c sshgssc.c \
		sshmd5.c sshpubk.c sshrand.c sshrsa.c sshsh256.c sshsh512.c \
		sshsha.c sshshare.c sshzlib.c telnet.c time.c timing.c \
		tree234.c unix/ux_x11.c unix/uxagentc.c unix/uxcons.c \
		unix/uxgss.c unix/uxmisc.c unix/uxnet.c unix/uxnogtk.c \
		unix/uxnoise.c unix/uxpeer.c unix/uxplink.c unix/uxproxy.c \
		unix/uxsel.c unix/uxser.c unix/uxshare.c unix/uxsignal.c \
		unix/uxstore.c wildcard.c x11fwd.c

plink_LDADD = libversion.a
pscp_SOURCES = aqsync.c be_misc.c be_ssh.c callback.c cmdline.c conf.c \
		cproxy.c int64.c logging.c misc.c pgssapi.c pinger.c \
		portfwd.c proxy.c pscp.c settings.c sftp.c ssh.c sshaes.c \
		ssharcf.c sshblowf.c sshbn.c sshccp.c sshcrc.c sshcrcda.c \
		sshdes.c sshdh.c sshdss.c sshecc.c sshgssc.c sshmd5.c \
		sshpubk.c sshrand.c sshrsa.c sshsh256.c sshsh512.c sshsha.c \
		sshshare.c sshzlib.c time.c timing.c tree234.c \
		unix/uxagentc.c unix/uxcons.c unix/uxgss.c unix/uxmisc.c \
		unix/uxnet.c unix/uxnogtk.c unix/uxnoise.c unix/uxpeer.c \
		unix/uxproxy.c unix/uxsel.c unix/uxsftp.c unix/uxshare.c \
		unix/uxstore.c wildcard.c x11fwd.c

pscp_LDADD = libversion.a
psftp_SOURCES = aqsync.c be_misc.c be_ssh.c callback.c cmdline.c conf.c \
		cproxy.c int64.c logging.c misc.c pgssapi.c pinger.c \
		portfwd.c proxy.c psftp.c settings.c sftp.c ssh.c sshaes.c \
		ssharcf.c sshblowf.c sshbn.c sshccp.c sshcrc.c sshcrcda.c \
		sshdes.c sshdh.c sshdss.c sshecc.c sshgssc.c sshmd5.c \
		sshpubk.c sshrand.c sshrsa.c sshsh256.c sshsh512.c sshsha.c \
		sshshare.c sshzlib.c time.c timing.c tree234.c \
		unix/uxagentc.c unix/uxcons.c unix/uxgss.c unix/uxmisc.c \
		unix/uxnet.c unix/uxnogtk.c unix/uxnoise.c unix/uxpeer.c \
		unix/uxproxy.c unix/uxsel.c unix/uxsftp.c unix/uxshare.c \
		unix/uxstore.c wildcard.c x11fwd.c

psftp_LDADD = libversion.a
pterm_SOURCES = be_none.c callback.c charset/fromucs.c charset/localenc.c \
		charset/macenc.c charset/mimeenc.c charset/sbcs.c \
		charset/sbcsdat.c charset/slookup.c charset/toucs.c \
		charset/utf8.c charset/xenc.c cmdline.c conf.c config.c \
		dialog.c ldisc.c ldiscucs.c logging.c minibidi.c misc.c \
		miscucs.c nocproxy.c nogss.c sercfg.c settings.c terminal.c \
		time.c timing.c tree234.c unix/gtkcfg.c unix/gtkcols.c \
		unix/gtkcomm.c unix/gtkdlg.c unix/gtkfont.c unix/gtkmain.c \
		unix/gtkmisc.c unix/gtkwin.c unix/uxcfg.c unix/uxmisc.c \
		unix/uxprint.c unix/uxpterm.c unix/uxpty.c unix/uxsel.c \
		unix/uxsignal.c unix/uxstore.c unix/uxucs.c unix/x11misc.c \
		unix/xkeysym.c unix/xpmptcfg.c unix/xpmpterm.c wcwidth.c

pterm_LDADD = libversion.a $(GTK_LIBS)
ptermapp_SOURCES = be_none.c callback.c charset/fromucs.c charset/localenc.c \
		charset/macenc.c charset/mimeenc.c charset/sbcs.c \
		charset/sbcsdat.c charset/slookup.c charset/toucs.c \
		charset/utf8.c charset/xenc.c cmdline.c conf.c config.c \
		dialog.c ldisc.c ldiscucs.c logging.c minibidi.c misc.c \
		miscucs.c nocproxy.c nogss.c sercfg.c settings.c terminal.c \
		time.c timing.c tree234.c unix/gtkapp.c unix/gtkcfg.c \
		unix/gtkcols.c unix/gtkcomm.c unix/gtkdlg.c unix/gtkfont.c \
		unix/gtkmisc.c unix/gtkwin.c unix/uxcfg.c unix/uxmisc.c \
		unix/uxprint.c unix/uxpterm.c unix/uxpty.c unix/uxsel.c \
		unix/uxsignal.c unix/uxstore.c unix/uxucs.c unix/x11misc.c \
		unix/xkeysym.c unix/xpmptcfg.c unix/xpmpterm.c wcwidth.c

ptermapp_LDADD = libversion.a $(GTK_LIBS)
putty_SOURCES = aqsync.c be_all_s.c be_misc.c callback.c charset/fromucs.c \
		charset/localenc.c charset/macenc.c charset/mimeenc.c \
		charset/sbcs.c charset/sbcsdat.c charset/slookup.c \
		charset/toucs.c charset/utf8.c charset/xenc.c cmdline.c \
		conf.c config.c cproxy.c dialog.c ldisc.c ldiscucs.c \
		logging.c minibidi.c misc.c miscucs.c pgssapi.c pinger.c \
		portfwd.c proxy.c raw.c rlogin.c sercfg.c settings.c ssh.c \
		sshaes.c ssharcf.c sshblowf.c sshbn.c sshccp.c sshcrc.c \
		sshcrcda.c sshdes.c sshdh.c sshdss.c sshecc.c sshgssc.c \
		sshmd5.c sshpubk.c sshrand.c sshrsa.c sshsh256.c sshsh512.c \
		sshsha.c sshshare.c sshzlib.c telnet.c terminal.c time.c \
		timing.c tree234.c unix/gtkcfg.c unix/gtkcols.c \
		unix/gtkcomm.c unix/gtkdlg.c unix/gtkfont.c unix/gtkmain.c \
		unix/gtkmisc.c unix/gtkwin.c unix/ux_x11.c unix/uxagentc.c \
		unix/uxcfg.c unix/uxgss.c unix/uxmisc.c unix/uxnet.c \
		unix/uxnoise.c unix/uxpeer.c unix/uxprint.c unix/uxproxy.c \
		unix/uxputty.c unix/uxsel.c unix/uxser.c unix/uxshare.c \
		unix/uxsignal.c unix/uxstore.c unix/uxucs.c unix/x11misc.c \
		unix/xkeysym.c unix/xpmpucfg.c unix/xpmputty.c wcwidth.c \
		wildcard.c x11fwd.c

putty_LDADD = libversion.a $(GTK_LIBS)
puttyapp_SOURCES = aqsync.c be_all_s.c be_misc.c callback.c \
		charset/fromucs.c charset/localenc.c charset/macenc.c \
		charset/mimeenc.c charset/sbcs.c charset/sbcsdat.c \
		charset/slookup.c charset/toucs.c charset/utf8.c \
		charset/xenc.c cmdline.c conf.c config.c cproxy.c dialog.c \
		ldisc.c ldiscucs.c logging.c minibidi.c misc.c miscucs.c \
		pgssapi.c pinger.c portfwd.c proxy.c raw.c rlogin.c sercfg.c \
		settings.c ssh.c sshaes.c ssharcf.c sshblowf.c sshbn.c \
		sshccp.c sshcrc.c sshcrcda.c sshdes.c sshdh.c sshdss.c \
		sshecc.c sshgssc.c sshmd5.c sshpubk.c sshrand.c sshrsa.c \
		sshsh256.c sshsh512.c sshsha.c sshshare.c sshzlib.c telnet.c \
		terminal.c time.c timing.c tree234.c unix/gtkapp.c \
		unix/gtkcfg.c unix/gtkcols.c unix/gtkcomm.c unix/gtkdlg.c \
		unix/gtkfont.c unix/gtkmisc.c unix/gtkwin.c unix/ux_x11.c \
		unix/uxagentc.c unix/uxcfg.c unix/uxgss.c unix/uxmisc.c \
		unix/uxnet.c unix/uxnoise.c unix/uxpeer.c unix/uxprint.c \
		unix/uxproxy.c unix/uxputty.c unix/uxsel.c unix/uxser.c \
		unix/uxshare.c unix/uxsignal.c unix/uxstore.c unix/uxucs.c \
		unix/x11misc.c unix/xkeysym.c unix/xpmpucfg.c \
		unix/xpmputty.c wcwidth.c wildcard.c x11fwd.c

puttyapp_LDADD = libversion.a $(GTK_LIBS)
puttygen_SOURCES = cmdgen.c conf.c import.c misc.c notiming.c sshaes.c \
		sshbcrypt.c sshblowf.c sshbn.c sshdes.c sshdss.c sshdssg.c \
		sshecc.c sshecdsag.c sshmd5.c sshprime.c sshpubk.c sshrand.c \
		sshrsa.c sshrsag.c sshsh256.c sshsh512.c sshsha.c time.c \
		tree234.c unix/uxcons.c unix/uxgen.c unix/uxmisc.c \
		unix/uxnogtk.c unix/uxnoise.c unix/uxstore.c

puttygen_LDADD = libversion.a
puttytel_SOURCES = be_misc.c be_nos_s.c callback.c charset/fromucs.c \
		charset/localenc.c charset/macenc.c charset/mimeenc.c \
		charset/sbcs.c charset/sbcsdat.c charset/slookup.c \
		charset/toucs.c charset/utf8.c charset/xenc.c cmdline.c \
		conf.c config.c dialog.c ldisc.c ldiscucs.c logging.c \
		minibidi.c misc.c miscucs.c nocproxy.c nogss.c pinger.c \
		proxy.c raw.c rlogin.c sercfg.c settings.c telnet.c \
		terminal.c time.c timing.c tree234.c unix/gtkcfg.c \
		unix/gtkcols.c unix/gtkcomm.c unix/gtkdlg.c unix/gtkfont.c \
		unix/gtkmain.c unix/gtkmisc.c unix/gtkwin.c unix/uxcfg.c \
		unix/uxmisc.c unix/uxnet.c unix/uxpeer.c unix/uxprint.c \
		unix/uxproxy.c unix/uxputty.c unix/uxsel.c unix/uxser.c \
		unix/uxsignal.c unix/uxstore.c unix/uxucs.c unix/x11misc.c \
		unix/xkeysym.c unix/xpmpucfg.c unix/xpmputty.c wcwidth.c

puttytel_LDADD = libversion.a $(GTK_LIBS)
testbn_SOURCES = conf.c misc.c sshbn.c testbn.c tree234.c unix/uxmisc.c \
		unix/uxnogtk.c

testbn_LDADD = libversion.a
#BUILT_SOURCES = empty.h
#CLEANFILES = empty.h
#man1_MANS = doc/plink.1 doc/pscp.1 doc/psftp.1 doc/puttygen.1
man1_MANS = doc/plink.1 doc/pscp.1 doc/psftp.1 doc/puttygen.1 \
	    doc/pageant.1 doc/pterm.1 doc/putty.1 doc/puttytel.1

#noinst_SCRIPTS = unix/PuTTY.app unix/Pterm.app
all: $(BUILT_SOURCES) uxconfig.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

uxconfig.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/uxconfig.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status uxconfig.h
$(srcdir)/uxconfig.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f uxconfig.h stamp-h1

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)

libversion.a: $(libversion_a_OBJECTS) $(libversion_a_DEPENDENCIES) $(EXTRA_libversion_a_DEPENDENCIES) 
	$(AM_V_at)-rm -f libversion.a
	$(AM_V_AR)$(libversion_a_AR) libversion.a $(libversion_a_OBJECTS) $(libversion_a_LIBADD)
	$(AM_V_at)$(RANLIB) libversion.a
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
unix/$(am__dirstamp):
	@$(MKDIR_P) unix
	@: > unix/$(am__dirstamp)
unix/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) unix/$(DEPDIR)
	@: > unix/$(DEPDIR)/$(am__dirstamp)
unix/uxcons.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxgen.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxmisc.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxnogtk.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxnoise.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxstore.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)

cgtest$(EXEEXT): $(cgtest_OBJECTS) $(cgtest_DEPENDENCIES) $(EXTRA_cgtest_DEPENDENCIES) 
	@rm -f cgtest$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(cgtest_OBJECTS) $(cgtest_LDADD) $(LIBS)
charset/$(am__dirstamp):
	@$(MKDIR_P) charset
	@: > charset/$(am__dirstamp)
charset/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) charset/$(DEPDIR)
	@: > charset/$(DEPDIR)/$(am__dirstamp)
charset/fromucs.$(OBJEXT): charset/$(am__dirstamp) \
	charset/$(DEPDIR)/$(am__dirstamp)
charset/localenc.$(OBJEXT): charset/$(am__dirstamp) \
	charset/$(DEPDIR)/$(am__dirstamp)
charset/macenc.$(OBJEXT): charset/$(am__dirstamp) \
	charset/$(DEPDIR)/$(am__dirstamp)
charset/mimeenc.$(OBJEXT): charset/$(am__dirstamp) \
	charset/$(DEPDIR)/$(am__dirstamp)
charset/sbcs.$(OBJEXT): charset/$(am__dirstamp) \
	charset/$(DEPDIR)/$(am__dirstamp)
charset/sbcsdat.$(OBJEXT): charset/$(am__dirstamp) \
	charset/$(DEPDIR)/$(am__dirstamp)
charset/slookup.$(OBJEXT): charset/$(am__dirstamp) \
	charset/$(DEPDIR)/$(am__dirstamp)
charset/toucs.$(OBJEXT): charset/$(am__dirstamp) \
	charset/$(DEPDIR)/$(am__dirstamp)
charset/utf8.$(OBJEXT): charset/$(am__dirstamp) \
	charset/$(DEPDIR)/$(am__dirstamp)
charset/xenc.$(OBJEXT): charset/$(am__dirstamp) \
	charset/$(DEPDIR)/$(am__dirstamp)
unix/uxcfg.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxprint.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxucs.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)

fuzzterm$(EXEEXT): $(fuzzterm_OBJECTS) $(fuzzterm_DEPENDENCIES) $(EXTRA_fuzzterm_DEPENDENCIES) 
	@rm -f fuzzterm$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(fuzzterm_OBJECTS) $(fuzzterm_LDADD) $(LIBS)
unix/osxlaunch.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)

osxlaunch$(EXEEXT): $(osxlaunch_OBJECTS) $(osxlaunch_DEPENDENCIES) $(EXTRA_osxlaunch_DEPENDENCIES) 
	@rm -f osxlaunch$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(osxlaunch_OBJECTS) $(osxlaunch_LDADD) $(LIBS)
unix/gtkask.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/gtkmisc.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/ux_x11.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxagentc.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxnet.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxpeer.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxpgnt.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxproxy.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxsel.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxsignal.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)

pageant$(EXEEXT): $(pageant_OBJECTS) $(pageant_DEPENDENCIES) $(EXTRA_pageant_DEPENDENCIES) 
	@rm -f pageant$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(pageant_OBJECTS) $(pageant_LDADD) $(LIBS)
unix/uxgss.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxplink.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxser.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxshare.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)

plink$(EXEEXT): $(plink_OBJECTS) $(plink_DEPENDENCIES) $(EXTRA_plink_DEPENDENCIES) 
	@rm -f plink$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(plink_OBJECTS) $(plink_LDADD) $(LIBS)
unix/uxsftp.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)

pscp$(EXEEXT): $(pscp_OBJECTS) $(pscp_DEPENDENCIES) $(EXTRA_pscp_DEPENDENCIES) 
	@rm -f pscp$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(pscp_OBJECTS) $(pscp_LDADD) $(LIBS)

psftp$(EXEEXT): $(psftp_OBJECTS) $(psftp_DEPENDENCIES) $(EXTRA_psftp_DEPENDENCIES) 
	@rm -f psftp$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(psftp_OBJECTS) $(psftp_LDADD) $(LIBS)
unix/gtkcfg.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/gtkcols.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/gtkcomm.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/gtkdlg.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/gtkfont.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/gtkmain.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/gtkwin.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxpterm.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/uxpty.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/x11misc.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/xkeysym.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/xpmptcfg.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/xpmpterm.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)

pterm$(EXEEXT): $(pterm_OBJECTS) $(pterm_DEPENDENCIES) $(EXTRA_pterm_DEPENDENCIES) 
	@rm -f pterm$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(pterm_OBJECTS) $(pterm_LDADD) $(LIBS)
unix/gtkapp.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)

ptermapp$(EXEEXT): $(ptermapp_OBJECTS) $(ptermapp_DEPENDENCIES) $(EXTRA_ptermapp_DEPENDENCIES) 
	@rm -f ptermapp$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(ptermapp_OBJECTS) $(ptermapp_LDADD) $(LIBS)
unix/uxputty.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/xpmpucfg.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)
unix/xpmputty.$(OBJEXT): unix/$(am__dirstamp) \
	unix/$(DEPDIR)/$(am__dirstamp)

putty$(EXEEXT): $(putty_OBJECTS) $(putty_DEPENDENCIES) $(EXTRA_putty_DEPENDENCIES) 
	@rm -f putty$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(putty_OBJECTS) $(putty_LDADD) $(LIBS)

puttyapp$(EXEEXT): $(puttyapp_OBJECTS) $(puttyapp_DEPENDENCIES) $(EXTRA_puttyapp_DEPENDENCIES) 
	@rm -f puttyapp$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(puttyapp_OBJECTS) $(puttyapp_LDADD) $(LIBS)

puttygen$(EXEEXT): $(puttygen_OBJECTS) $(puttygen_DEPENDENCIES) $(EXTRA_puttygen_DEPENDENCIES) 
	@rm -f puttygen$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(puttygen_OBJECTS) $(puttygen_LDADD) $(LIBS)

puttytel$(EXEEXT): $(puttytel_OBJECTS) $(puttytel_DEPENDENCIES) $(EXTRA_puttytel_DEPENDENCIES) 
	@rm -f puttytel$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(puttytel_OBJECTS) $(puttytel_LDADD) $(LIBS)

testbn$(EXEEXT): $(testbn_OBJECTS) $(testbn_DEPENDENCIES) $(EXTRA_testbn_DEPENDENCIES) 
	@rm -f testbn$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(testbn_OBJECTS) $(testbn_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f charset/*.$(OBJEXT)
	-rm -f unix/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/aqsync.Po
include ./$(DEPDIR)/be_all_s.Po
include ./$(DEPDIR)/be_misc.Po
include ./$(DEPDIR)/be_none.Po
include ./$(DEPDIR)/be_nos_s.Po
include ./$(DEPDIR)/be_ssh.Po
include ./$(DEPDIR)/callback.Po
include ./$(DEPDIR)/cgtest.Po
include ./$(DEPDIR)/cmdgen.Po
include ./$(DEPDIR)/cmdline.Po
include ./$(DEPDIR)/conf.Po
include ./$(DEPDIR)/config.Po
include ./$(DEPDIR)/cproxy.Po
include ./$(DEPDIR)/dialog.Po
include ./$(DEPDIR)/fuzzterm.Po
include ./$(DEPDIR)/import.Po
include ./$(DEPDIR)/int64.Po
include ./$(DEPDIR)/ldisc.Po
include ./$(DEPDIR)/ldiscucs.Po
include ./$(DEPDIR)/libversion_a-version.Po
include ./$(DEPDIR)/logging.Po
include ./$(DEPDIR)/minibidi.Po
include ./$(DEPDIR)/misc.Po
include ./$(DEPDIR)/miscucs.Po
include ./$(DEPDIR)/nocproxy.Po
include ./$(DEPDIR)/nogss.Po
include ./$(DEPDIR)/noterm.Po
include ./$(DEPDIR)/notiming.Po
include ./$(DEPDIR)/pageant.Po
include ./$(DEPDIR)/pgssapi.Po
include ./$(DEPDIR)/pinger.Po
include ./$(DEPDIR)/portfwd.Po
include ./$(DEPDIR)/proxy.Po
include ./$(DEPDIR)/pscp.Po
include ./$(DEPDIR)/psftp.Po
include ./$(DEPDIR)/raw.Po
include ./$(DEPDIR)/rlogin.Po
include ./$(DEPDIR)/sercfg.Po
include ./$(DEPDIR)/settings.Po
include ./$(DEPDIR)/sftp.Po
include ./$(DEPDIR)/ssh.Po
include ./$(DEPDIR)/sshaes.Po
include ./$(DEPDIR)/ssharcf.Po
include ./$(DEPDIR)/sshbcrypt.Po
include ./$(DEPDIR)/sshblowf.Po
include ./$(DEPDIR)/sshbn.Po
include ./$(DEPDIR)/sshccp.Po
include ./$(DEPDIR)/sshcrc.Po
include ./$(DEPDIR)/sshcrcda.Po
include ./$(DEPDIR)/sshdes.Po
include ./$(DEPDIR)/sshdh.Po
include ./$(DEPDIR)/sshdss.Po
include ./$(DEPDIR)/sshdssg.Po
include ./$(DEPDIR)/sshecc.Po
include ./$(DEPDIR)/sshecdsag.Po
include ./$(DEPDIR)/sshgssc.Po
include ./$(DEPDIR)/sshmd5.Po
include ./$(DEPDIR)/sshprime.Po
include ./$(DEPDIR)/sshpubk.Po
include ./$(DEPDIR)/sshrand.Po
include ./$(DEPDIR)/sshrsa.Po
include ./$(DEPDIR)/sshrsag.Po
include ./$(DEPDIR)/sshsh256.Po
include ./$(DEPDIR)/sshsh512.Po
include ./$(DEPDIR)/sshsha.Po
include ./$(DEPDIR)/sshshare.Po
include ./$(DEPDIR)/sshzlib.Po
include ./$(DEPDIR)/telnet.Po
include ./$(DEPDIR)/terminal.Po
include ./$(DEPDIR)/testbn.Po
include ./$(DEPDIR)/time.Po
include ./$(DEPDIR)/timing.Po
include ./$(DEPDIR)/tree234.Po
include ./$(DEPDIR)/wcwidth.Po
include ./$(DEPDIR)/wildcard.Po
include ./$(DEPDIR)/x11fwd.Po
include charset/$(DEPDIR)/fromucs.Po
include charset/$(DEPDIR)/localenc.Po
include charset/$(DEPDIR)/macenc.Po
include charset/$(DEPDIR)/mimeenc.Po
include charset/$(DEPDIR)/sbcs.Po
include charset/$(DEPDIR)/sbcsdat.Po
include charset/$(DEPDIR)/slookup.Po
include charset/$(DEPDIR)/toucs.Po
include charset/$(DEPDIR)/utf8.Po
include charset/$(DEPDIR)/xenc.Po
include unix/$(DEPDIR)/gtkapp.Po
include unix/$(DEPDIR)/gtkask.Po
include unix/$(DEPDIR)/gtkcfg.Po
include unix/$(DEPDIR)/gtkcols.Po
include unix/$(DEPDIR)/gtkcomm.Po
include unix/$(DEPDIR)/gtkdlg.Po
include unix/$(DEPDIR)/gtkfont.Po
include unix/$(DEPDIR)/gtkmain.Po
include unix/$(DEPDIR)/gtkmisc.Po
include unix/$(DEPDIR)/gtkwin.Po
include unix/$(DEPDIR)/osxlaunch.Po
include unix/$(DEPDIR)/ux_x11.Po
include unix/$(DEPDIR)/uxagentc.Po
include unix/$(DEPDIR)/uxcfg.Po
include unix/$(DEPDIR)/uxcons.Po
include unix/$(DEPDIR)/uxgen.Po
include unix/$(DEPDIR)/uxgss.Po
include unix/$(DEPDIR)/uxmisc.Po
include unix/$(DEPDIR)/uxnet.Po
include unix/$(DEPDIR)/uxnogtk.Po
include unix/$(DEPDIR)/uxnoise.Po
include unix/$(DEPDIR)/uxpeer.Po
include unix/$(DEPDIR)/uxpgnt.Po
include unix/$(DEPDIR)/uxplink.Po
include unix/$(DEPDIR)/uxprint.Po
include unix/$(DEPDIR)/uxproxy.Po
include unix/$(DEPDIR)/uxpterm.Po
include unix/$(DEPDIR)/uxpty.Po
include unix/$(DEPDIR)/uxputty.Po
include unix/$(DEPDIR)/uxsel.Po
include unix/$(DEPDIR)/uxser.Po
include unix/$(DEPDIR)/uxsftp.Po
include unix/$(DEPDIR)/uxshare.Po
include unix/$(DEPDIR)/uxsignal.Po
include unix/$(DEPDIR)/uxstore.Po
include unix/$(DEPDIR)/uxucs.Po
include unix/$(DEPDIR)/x11misc.Po
include unix/$(DEPDIR)/xkeysym.Po
include unix/$(DEPDIR)/xpmptcfg.Po
include unix/$(DEPDIR)/xpmpterm.Po
include unix/$(DEPDIR)/xpmpucfg.Po
include unix/$(DEPDIR)/xpmputty.Po

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

libversion_a-version.o: version.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libversion_a_CFLAGS) $(CFLAGS) -MT libversion_a-version.o -MD -MP -MF $(DEPDIR)/libversion_a-version.Tpo -c -o libversion_a-version.o `test -f 'version.c' || echo '$(srcdir)/'`version.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/libversion_a-version.Tpo $(DEPDIR)/libversion_a-version.Po
#	$(AM_V_CC)source='version.c' object='libversion_a-version.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libversion_a_CFLAGS) $(CFLAGS) -c -o libversion_a-version.o `test -f 'version.c' || echo '$(srcdir)/'`version.c

libversion_a-version.obj: version.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libversion_a_CFLAGS) $(CFLAGS) -MT libversion_a-version.obj -MD -MP -MF $(DEPDIR)/libversion_a-version.Tpo -c -o libversion_a-version.obj `if test -f 'version.c'; then $(CYGPATH_W) 'version.c'; else $(CYGPATH_W) '$(srcdir)/version.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/libversion_a-version.Tpo $(DEPDIR)/libversion_a-version.Po
#	$(AM_V_CC)source='version.c' object='libversion_a-version.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libversion_a_CFLAGS) $(CFLAGS) -c -o libversion_a-version.obj `if test -f 'version.c'; then $(CYGPATH_W) 'version.c'; else $(CYGPATH_W) '$(srcdir)/version.c'; fi`
install-man1: $(man1_MANS)
	@$(NORMAL_INSTALL)
	@list1='$(man1_MANS)'; \
	list2=''; \
	test -n "$(man1dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man1dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man1dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.1[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
	done; }

uninstall-man1:
	@$(NORMAL_UNINSTALL)
	@list='$(man1_MANS)'; test -n "$(man1dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	dir='$(DESTDIR)$(man1dir)'; $(am__uninstall_files_from_dir)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-am
all-am: Makefile $(LIBRARIES) $(PROGRAMS) $(SCRIPTS) $(MANS) \
		uxconfig.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f charset/$(DEPDIR)/$(am__dirstamp)
	-rm -f charset/$(am__dirstamp)
	-rm -f unix/$(DEPDIR)/$(am__dirstamp)
	-rm -f unix/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
install-exec-local:
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-noinstLIBRARIES \
	clean-noinstPROGRAMS mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR) charset/$(DEPDIR) unix/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-man

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS install-exec-local

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man: install-man1

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR) charset/$(DEPDIR) unix/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-man

uninstall-man: uninstall-man1

.MAKE: all check install install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic \
	clean-noinstLIBRARIES clean-noinstPROGRAMS cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-exec-local install-html \
	install-html-am install-info install-info-am install-man \
	install-man1 install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic pdf pdf-am \
	ps ps-am tags tags-am uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-man uninstall-man1

.PRECIOUS: Makefile

#empty.h: $(allsources)
#	echo '/* Empty file touched by automake makefile to force rebuild of version.o */' >$@
#install-exec-local:
#	 $(bindir)/pterm
#	chmod  $(bindir)/pterm
#unix/PuTTY.app: unix/putty.bundle puttyapp osxlaunch
#	rm -rf $@ && gtk-mac-bundler $<
#unix/Pterm.app: unix/pterm.bundle ptermapp osxlaunch
#	rm -rf $@ && gtk-mac-bundler $<

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
